src/AmrodWCIntegration/Pages/CategoryImport.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

using AmrodWCIntegration.Clients.Amrod;
using AmrodWCIntegration.Clients.Wordpress;
using AmrodWCIntegration.Models.Amrod;
using AmrodWCIntegration.Services;
using AmrodWCIntegration.Utils;

using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

using WooCommerceNET.WooCommerce.v3;

namespace AmrodWCIntegration.Pages
{
    public class CategoryImportModel : PageModel
    {
        private readonly ILogger<CategoryImportModel> _logger;
        private readonly WoocommerceClient woocommerce;
        private readonly AmrodClient amrod;
        private readonly WcAmrodSync _wcAmrodSync;

        public ProductCategory wcCategory;
        public AmrodCategory amrodCategory;
        public Dictionary<int, string> Progress = new Dictionary<int, string>();
        public string StatusMessage = string.Empty;

        public CategoryImportModel(ILogger<CategoryImportModel> logger, WoocommerceClient woocommerceClient, AmrodClient amrodClient, WcAmrodSync wcAmrodSync)
        {
            _logger = logger;
            woocommerce = woocommerceClient;
            amrod = amrodClient;
            _wcAmrodSync = wcAmrodSync;
        }

        public async Task<IActionResult> OnGetAsync(int categoryId, string requestId = null)
        {
            amrodCategory = SessionHelper.GetObjectFromJson<AmrodCategory>(HttpContext.Session, "amrodCategory");
            wcCategory = SessionHelper.GetObjectFromJson<ProductCategory>(HttpContext.Session, "wcCategory");
            if ((amrodCategory == null || wcCategory == null) || amrodCategory?.CategoryId != categoryId)
            {
                amrodCategory = await amrod.GetCategoryAsync(categoryId);
                wcCategory = await woocommerce.GetCategory(amrodCategory.CategoryName);
                SessionHelper.SetObjectAsJson(HttpContext.Session, "amrodCategory", amrodCategory);
                SessionHelper.SetObjectAsJson(HttpContext.Session, "wcCategory", wcCategory);
            }

            if (!string.IsNullOrEmpty(requestId))
            {
                StatusMessage = ProgressTracker.GetValue(requestId).ToString();
                if (StatusMessage == "done")
                {
                    StatusMessage = "Import complete!!";
                }
                else if (StatusMessage.StartsWith("An Error occured"))
                {
                    //TODO: Improve how we handle this
                }
                else
                {
                    Response.Headers.Add("Refresh", "5");
                }
                Progress = SessionHelper.GetObjectFromJson<Dictionary<int, string>>(HttpContext.Session, "progress");
                Progress.Add(Progress.Count+1, StatusMessage);
                SessionHelper.SetObjectAsJson(HttpContext.Session, "progress", Progress);
                return Page();
            }
            else
            {
                requestId = Guid.NewGuid().ToString();
                ProgressTracker.Add(requestId, $"{DateTimeOffset.UtcNow} :: Starting Import!!!");
                Progress.Add(Progress.Count + 1,"Starting Import!!!");
                SessionHelper.SetObjectAsJson(HttpContext.Session, "progress", Progress);
                //Call Long running task
                _wcAmrodSync.RunTask(new Func<Task>(() => _wcAmrodSync.ImportCategoryProducts(amrodCategory, wcCategory)), requestId);
                
            }

            return RedirectToPage(new { requestId = requestId.ToString() });
        }
    }
}

src/AmrodWCIntegration/Pages/Error.cshtml.cs
// ==========================================================================
//  Amrod Woocommerce Integration
// ==========================================================================
//  Copyright (c) AmrodIntegration (Henko Rabie)
//  All rights reserved. Licensed under the GNU General Public License.
// ==========================================================================

using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace AmrodWCIntegration.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

src/AmrodWCIntegration/Pages/Index.cshtml.cs
// ==========================================================================
//  Amrod Woocommerce Integration
// ==========================================================================
//  Copyright (c) AmrodIntegration (Henko Rabie)
//  All rights reserved. Licensed under the GNU General Public License.
// ==========================================================================

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

using AmrodWCIntegration.Clients.Amrod;
using AmrodWCIntegration.Clients.Wordpress;
using AmrodWCIntegration.Models.Amrod;
using AmrodWCIntegration.Services;

using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

using WooCommerceNET.WooCommerce.v3;

namespace AmrodWCIntegration.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;
        private readonly WoocommerceClient woocommerce;
        private readonly AmrodClient amrod;
        private readonly WcAmrodSync _wcAmrodSync;

        public List<ProductCategory> Categories;
        public IEnumerable<AmrodCategory> AmrodCategories;
        
        public IndexModel(ILogger<IndexModel> logger, WoocommerceClient woocommerceClient, AmrodClient amrodClient, WcAmrodSync wcAmrodSync)
        {
            _logger = logger;
            woocommerce = woocommerceClient;
            amrod = amrodClient;
            _wcAmrodSync = wcAmrodSync;
        }

        public async Task OnGet()
        {
            AmrodCategories = await amrod.GetAllCategoriesAsync();
            Categories = await woocommerce.GetCategories();
            //await _wcAmrodSync.ImportCategoriesAsync();
            //await _wcAmrodSync.ImportProductsAsync();
        }

        public async Task OnPostImportCategories()
        {
            await _wcAmrodSync.ImportCategoriesAsync();
            AmrodCategories = await amrod.GetAllCategoriesAsync();
            Categories = await woocommerce.GetCategories();
        }
    }
}

src/AmrodWCIntegration/Pages/UpdateStockLevels.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

using AmrodWCIntegration.Services;
using AmrodWCIntegration.Utils;

using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace AmrodWCIntegration.Pages
{
    public class UpdateStockLevelsModel : PageModel
    {
        private readonly ILogger<UpdateStockLevelsModel> _logger;
        public Dictionary<int, string> Progress = new Dictionary<int, string>();
        public string StatusMessage = string.Empty;
        private readonly WcAmrodSync _wcAmrodSync;

        public UpdateStockLevelsModel(ILogger<UpdateStockLevelsModel> logger, WcAmrodSync wcAmrodSync)
        {
            _logger = logger;
            _wcAmrodSync = wcAmrodSync;
        }

        public async Task<IActionResult> OnGetAsync(string requestId = null)
        {
            if (!string.IsNullOrEmpty(requestId))
            {
                StatusMessage = ProgressTracker.GetValue(requestId).ToString();
                if (StatusMessage == "done")
                {
                    StatusMessage = "Stock Levels Update complete!!";
                }
                else if (StatusMessage.StartsWith("An Error occured"))
                {
                    //TODO: Improve how we handle this
                }
                else
                {
                    Response.Headers.Add("Refresh", "5");
                }
                Progress = SessionHelper.GetObjectFromJson<Dictionary<int, string>>(HttpContext.Session, "progress");
                Progress.Add(Progress.Count + 1, StatusMessage);
                SessionHelper.SetObjectAsJson(HttpContext.Session, "progress", Progress);
                return Page();
            }
            else
            {
                requestId = Guid.NewGuid().ToString();
                ProgressTracker.Add(requestId, $"{DateTimeOffset.UtcNow} :: Starting Stock Levels Update!!!");
                Progress.Add(Progress.Count + 1, "Starting Stock Levels Update!!!");
                SessionHelper.SetObjectAsJson(HttpContext.Session, "progress", Progress);
                //Call Long running task
                _wcAmrodSync.RunTask(new Func<Task>(() => _wcAmrodSync.UpdateStockLevels()), requestId);

            }

            return RedirectToPage(new { requestId = requestId.ToString() });
        }
    }
}

src/AmrodWCIntegration/Pages/CategoryImport.cshtml
@page "{categoryId:int}"
@model AmrodWCIntegration.Pages.CategoryImportModel
@{
}

<h1>Import Category - @Model.amrodCategory.CategoryName</h1>

<div class="text-center">
    <div class="alert alert-info" role="alert">
        @Model.StatusMessage
    </div>
    <div>
        <ul class="list-group list-group-flush">
            @foreach (var item in Model.Progress.OrderByDescending(x => x.Key))
            {
                <li class="list-group-item">@item.Value</li>
            }
        </ul>
    </div>
</div>

src/AmrodWCIntegration/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Dashboard</h1>
</div>
<div class="text-center p-2">
    <form method="post" asp-page="Index">
        <button type="submit" class="btn btn-primary" asp-page-handler="ImportCategories">IMPORT CATEGORIES</button>
    </form>
    <a asp-page="./UpdateStockLevels" class="btn btn-outline-primary">UPDATE STOCK LEVELS</a>
</div>
<div>
    <table class="table table-hover">
        <thead class="thead-dark">
            <tr>
                <th scope="col">Id</th>
                <th scope="col">Name</th>
                <th scope="col">Products</th>
                <th scope="col">WooCommerce</th>
                <th scope="col">WC Products</th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var amrodCategory in Model.AmrodCategories.Where(x => x.SubCategories.Count() == 0).OrderBy(x => x.CategoryName))
            {
            <tr class="@(
                    amrodCategory.ProductCount == Model.Categories?.FirstOrDefault(x => x.name == amrodCategory.CategoryName)?.count ? 
                    "table-success" : 
                    Model.Categories?.FirstOrDefault(x => x.name == amrodCategory.CategoryName)?.count > amrodCategory.ProductCount ? 
                    "table-danger" : 
                    Model.Categories?.FirstOrDefault(x => x.name == amrodCategory.CategoryName)?.count > 0 ? "table-warning" : "")">

                <th scope="row">@amrodCategory.CategoryId</th>
                <td>@amrodCategory.CategoryName</td>
                <td>@(amrodCategory.SubCategories.Count() != 0 ? 0 : amrodCategory.ProductCount)</td>
                <td>@Model.Categories.Any(x => x.name == amrodCategory.CategoryName)</td>
                <td>@Model.Categories?.FirstOrDefault(x => x.name == amrodCategory.CategoryName)?.count</td>
                <td>
                    @if (amrodCategory.SubCategories.Count() == 0 && Model.Categories.Any(x => x.name == amrodCategory.CategoryName))
                    {
                        <a asp-page="./CategoryImport" asp-route-categoryId="@amrodCategory.CategoryId" class="btn btn-outline-primary">Import Products</a>
                    }
                </td>
            </tr>
            }
        </tbody>
    </table>
</div>

src/AmrodWCIntegration/Pages/UpdateStockLevels.cshtml
@page 
@model AmrodWCIntegration.Pages.UpdateStockLevelsModel
@{
}

<h1>Update Stock Levels</h1>

<div class="text-center">
    <div class="alert alert-info" role="alert">
        @Model.StatusMessage
    </div>
    <div>
        <ul class="list-group list-group-flush">
            @foreach (var item in Model.Progress.OrderByDescending(x => x.Key))
            {
                <li class="list-group-item">@item.Value</li>
            }
        </ul>
    </div>
</div>